services:
  - type: web
    name: crop-recommendation-service
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python crop_recommendation_service.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 5000
    healthCheckPath: /health
    autoDeploy: true

