[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["maven", "jdk17"]

[build.nixpacksPlan.phases.build]
cmds = ["mvn clean package -DskipTests"]

[build.nixpacksPlan.phases.start]
cmd = "java -Dserver.port=$PORT -jar target/demo-0.0.1-SNAPSHOT.jar"
