[build]
builder = "nixpacks"

[build.nixpacksPlan]
providers = ["java"]

[build.nixpacksPlan.phases.setup]
nixPkgs = ["maven", "jdk17"]

[build.nixpacksPlan.phases.build]
cmds = ["mvn clean package -DskipTests"]

[deploy]
startCommand = "java -Dserver.port=$PORT -jar target/demo-0.0.1-SNAPSHOT.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/actuator/health"
timeout = 300
interval = 30

