# Nixpacks configuration for Railway
# This file tells Railway to use the demoSmartFarm/demo directory for the Java backend

[phases.setup]
nixPkgs = ["...", "jdk17"]

[phases.build]
cmds = [
  "cd demoSmartFarm/demo",
  "mvn clean package -DskipTests"
]

[start]
cmd = "cd demoSmartFarm/demo && java -Dserver.port=$PORT -jar target/demo-0.0.1-SNAPSHOT.jar"

