[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python39"]

[build.nixpacksPlan.phases.install]
cmds = ["pip install -r requirements.txt"]

[build.nixpacksPlan.phases.start]
cmd = "python pest_disease_service.py"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
startCommand = "python pest_disease_service.py"

