services:
  - type: web
    name: pest-disease-detection
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python pest_disease_service.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 5001
    healthCheckPath: /health
    autoDeploy: true

